const layers = [
  {
    id: 'lPPp_UG-RcbVdNFm9jgfx',
    isEditingText: false,
    isVisible: true,
    name: 'Box Layer',
    styleBackgroundColor: 'rgba(0,0,0,1)',
    styleHeight: 702,
    styleLeft: 299,
    styleOpacity: 100,
    styleTop: 789,
    styleWidth: 1132,
    type: 'box',
  },
  {
    id: 'y6EqeauHC7q9IK3xJ8dAa',
    isEditingText: false,
    isVisible: true,
    name: 'Text Layer',
    styleBackgroundColor: 'rgba(0,0,0,0)',
    styleColor: '#d0021bff',
    styleFontFamily: 'Work Sans',
    styleFontSize: 48,
    styleFontStyle: 'normal',
    styleFontWeight: '400',
    styleHeight: 74,
    styleLeft: 345.7672419069901,
    styleLetterSpacing: 0.5,
    styleLineHeight: 20,
    styleOpacity: 100,
    styleTextOverflow: 'ellipsis',
    styleTop: 921.4820385560166,
    styleWidth: 483,
    textValue: 'some text',
    type: 'text',
  },
  {
    fileName: 'Veterian-Fed-Checkbox-Image.png',
    filePath: 'ul8McNxcefAlD23AjrMh/images/Veterian-Fed-Checkbox-Image.png',
    fileUrl:
      'https://firebasestorage.googleapis.com/v0/b/factorfunction.appspot.com/o/ul8McNxcefAlD23AjrMh%2Fimages%2FVeterian-Fed-Checkbox-Image.png?alt=media&token=1591ba82-9a10-42e3-9c82-fc1910d4634e',
    id: 'dXLboU1E-IG57MqiR8D3r',
    isEditingText: false,
    isVisible: true,
    name: 'Image Layer',
    styleBackgroundColor: 'rgba(0,0,0,0)',
    styleBackgroundImage: '',
    styleBackgroundSize: 'cover',
    styleHeight: 54,
    styleHeightRatio: 0.15789473684210525,
    styleLeft: 365,
    styleOpacity: 100,
    styleOriginalHeight: 54,
    styleOriginalWidth: 342,
    styleTop: 999,
    styleWidth: 342,
    type: 'image',
  },
  {
    fileName: 'Raised-Humanely-Checkbox-Image.png',
    filePath: 'ul8McNxcefAlD23AjrMh/images/Raised-Humanely-Checkbox-Image.png',
    fileUrl:
      'https://firebasestorage.googleapis.com/v0/b/factorfunction.appspot.com/o/ul8McNxcefAlD23AjrMh%2Fimages%2FRaised-Humanely-Checkbox-Image.png?alt=media&token=7955b8e4-045b-4da5-b8c6-e9d842f2fe70',
    id: 'Xcl8iIJrMhpxfSihvQbQ6',
    isEditingText: false,
    isVisible: true,
    name: 'Image Layer',
    styleBackgroundColor: 'rgba(0,0,0,0)',
    styleBackgroundImage: '',
    styleBackgroundSize: 'cover',
    styleHeight: 54,
    styleHeightRatio: 0.12356979405034325,
    styleLeft: 363,
    styleOpacity: 100,
    styleOriginalHeight: 54,
    styleOriginalWidth: 437,
    styleTop: 1079,
    styleWidth: 437,
    type: 'image',
  },
]
